results-storage:
  build: build/docker
  links:
    - zookeeper:zk
    - graphite:gr

  environment:
    spring.profiles.active: prod
    APP_ENV: prod

  command: --service.resolver.url=zk:2181 \
           --graphite.host=gr

  ports:
    - 0.0.0.0:8095:8095
